 
variables:
    - name: yamlvar
      value : i am yaml variable
    - group : somevargroup
pool:
  name: Default


stages:
  - stage: DevStage
    jobs:
      - job: getlatest
        steps:
          - script: |
             echo $(yamlvar)
             echo $(inputvar)
             echo $(vargroup1)
             echo "##vso[task.setvariable variable=yamlvar;]this yaml var is changed"
             echo $(yamlvar)
            displayName: Step1
            name: StepName1
          - script: |
             echo $(yamlvar)
            displayName: Step2 
            name: StepName2

      - job: buildstage
        steps:
          - script : |
             echo $(yamlvar)
            displayName: Step3
            name: StepName3

  - stage: TestStage
    jobs:
      - job: preparingingdata
        steps:
          - script: 
             echo teststagepreparingdatastep1


