variables: 
  - group: vargroup
  - name: connstr
    value: test

parameters:
  - name: environment
    displayName: Which Environment to deploy?
    type: string
    default: 'develop'
    values:
    - develop
    - preproduction
    - production

pool:
  name: Default
  

steps:
- script: |
   echo Hello, $(inputvar)
   echo variable group $(var1)
  displayName: 'stage1'

- powershell: 
    write-Host Hello from powershell $(connstr) 
  displayName: 'stage2'

- script: |
    echo Hello from script $(connstr)
  displayName: stage3
