variables:
  connstr: test

pool:
  name: Default
  

steps:
- script: |
   echo Hello, $(connstr)
  displayName: 'stage1'

- powershell: 
    write-Host from powershell $(connstr) 
  displayName: 'stage2'

- script: |
    echo Hello from script $(connstr)
  displayName: stage3
