pool:
  name: Default

stages:
  - stage: DevStage
    jobs:
      - job: getlatest
        steps:
          - script: |
             echo stage1job1step1
            displayName: Step1 
      - job: buildstage
        steps:
          - script : |
             echo stage1job2step2
            displayName: Step2

  - stage: TestStage
    jobs:
      - job: preparingingdata
        steps:
          - script: 
             echo teststagepreparingdatastep1


