variables:
  conn: test

pool:
  name: Default
  

steps:
- script: |
   echo Hello, world!
  displayName: 'stage1'

- powershell: 
    write-Host Add other tasks to build, test, and deploy your project.
  displayName: 'stage2'

- script: |
    echo Hello from script
  displayName: stage3
